export enum TimeUnits {
  years = 'years',
  year = 'year',
  months = 'months',
  month = 'month',
  days = 'days',
  day = 'day',
  hour = 'hour',
  hours = 'hours',
  minutes = 'minutes',
  minute = 'minute',
  seconds = 'seconds',
  second = 'second',
  milliseconds = 'milliseconds',
  millisecond = 'millisecond',
}
