export { ReactComponent as coursesListIcon } from './coursesList.svg';
export { ReactComponent as myCoursesIcon } from './myCourses.svg';
export { ReactComponent as helpIcon } from './helpIcon.svg';
export { ReactComponent as pendingIcon } from './pendingIcon.svg';
export { ReactComponent as employeeIcon } from './employeeIcon.svg';
export { ReactComponent as skillsIcon } from './skillsIcon.svg';
export { ReactComponent as leftArrow } from './leftArrow.svg';
export { ReactComponent as rightArrow } from './rightArrow.svg';
export { ReactComponent as assessmentsIcon } from './pendingAssessments.svg';
