const MIN_TITLE_LENGTH = 2;
const MAX_TITLE_LENGTH = 100;

const FIRST_LETTER_INDEX = 0;
const SECOND_LETTER_INDEX = 1;

export { MIN_TITLE_LENGTH, MAX_TITLE_LENGTH, FIRST_LETTER_INDEX, SECOND_LETTER_INDEX };
