export const QUERY_KEYS = {
  courseAndMaterials: 'CourseAndMaterials',
  courseInfo: 'CourseInfo',
  paginatedCoursesList: 'PaginatedCoursesList',
  myCourses: 'MyCourses',
  employeeProfile: 'EmployeeProfile',
  coursesRequests: 'CoursesRequests',
  employeesList: 'EmployeesList',
  profile: 'Profile',
  clientCourseInfo: 'ClientCourseInfo',
  paginatedClientCoursesList: 'PaginatedClientCoursesList',
  courseTest: 'CourseTest',
  getTestTime: 'GetTestTime',
  skills: 'Skills',
};
