export const PATHS: {
  home: string;
  profile: string;
  coursesList: string;
  courseDetails: string;
  myCourses: string;
  myCourseDetails: string;
  course: string;
  help: string;
  signIn: string;
  requests: string;
  employees: string;
  employee: string;
  employeeProfile: string;
  skills: string;
  notFound: string;
  learnCourse: string;
  learnCourseTest: string;
  learnClientCourse: string;
  courseTest: string;
  skillsMap: string;
  pendingAssessments: string;
  courseEditor: string;
  courseCreator: string;
} = {
  home: '/',
  profile: '/profile',
  coursesList: '/courses-list',
  courseDetails: '/courses-list/:courseId',
  myCourses: '/my-courses',
  myCourseDetails: '/my-courses/:clientCourseId',
  course: ':courseId',
  help: '/help',
  signIn: '/signin',
  requests: '/pending-requests',
  employees: '/employees',
  employee: ':employeeId',
  employeeProfile: '/employees/:employeeId',
  skills: '/skills',
  notFound: '/not-found',
  learnCourse: '/my-courses/learn/:courseId',
  learnCourseTest: '/my-courses/learn/:courseId/test',
  learnClientCourse: 'learn/:courseId',
  courseTest: 'learn/:courseId/test',
  skillsMap: '/skills-map',
  pendingAssessments: '/pending-assessments',
  courseEditor: '/:courseId/editor',
  courseCreator: '/create-course',
};

export const API: {
  getProfile: string;
  readNotifications: string;
  getToken: string;
  courses: string;
  coursesMap: string;
  getCoursesRequests: string;
  getEmployeesList: string;
  approveRequest: string;
  declineRequest: string;
  getMyCourses: string;
  logOut: string;
  employees: string;
  refresh: string;
  skills: string;
  manageAssessment: string;
  getPendingAssessments: string;
  tests: string;
  createCourse: string;
  editCourse: string;
} = {
  getProfile: '/api/users',
  readNotifications: '/api/users/notifications',
  getToken: '/api/account/login',
  courses: '/api/courses',
  coursesMap: '/api/courses/map',
  getCoursesRequests: '/api/pendingCourses',
  getEmployeesList: '/api/employees',
  approveRequest: '/api/pendingCourses/approveCourse',
  declineRequest: '/api/pendingCourses/declineCourse',
  getMyCourses: '/api/clientCourses',
  logOut: '/api/account/logout',
  employees: '/api/employees',
  refresh: '/api/account/refresh',
  skills: '/api/skills',
  manageAssessment: 'api/clientCourses/:id/assessment',
  getPendingAssessments: 'api/clientCourses/assessments',
  tests: 'api/tests',
  createCourse: '/api/courses/create',
  editCourse: 'api/courses/:id/edit',
};
