export const SELECTS_OPTIONS = {
  technologies: [
    'Android',
    'Angular',
    'Bootstrap',
    'C#',
    'C++',
    'CSS',
    'Django',
    'English',
    'Go',
    'HTML',
    'Java',
    'JavaScript',
    'jQuery',
    'Kotlin',
    'Math',
    'MySQL',
    'NodeJS',
    'PHP',
    'Pandas',
    'Python',
    'ReactJS',
    'Ruby',
    'SQL',
    'Salesforce',
    'Scala',
    'TypeScript',
    'Unity',
    'VueJS',
  ],
  status: [
    'Approved',
    'Assessment',
    'Completed',
    'Failed',
    'Pending',
    'Rejected',
    'Started',
    'Testing',
  ],
  complexity: ['Junior', 'Middle', 'Senior'],
};
