export enum ButtonLabels {
  applyCourse = 'Apply the Course',
  applyTheCourse = 'Apply the course',
  startTest = 'Start the Test',
  details = 'Details',
  stay = 'Stay',
  exit = 'Exit',
  ok = 'OK',
  previous = 'Previous',
  result = 'Result',
  back = 'Back',
  stay = 'Stay',
  next = 'Next',
  exit = 'Exit',
  add = 'Add',
  submit = 'Submit',
  addWithPlus = '+Add',
  addCourse = '+ Add course',
  skills = 'Skills',
  allCourses = 'All courses',
  lookInFull = 'Look in full',
  loading = 'Loading...',
  login = 'LOG IN',
  cancel = 'Cancel',
}
