export const COURSE_TEXT = [
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed egestas lobortis lacus sed sodales. Aenean pharetra, purus sit amet ornare tempor, mi lectus aliquam risus, in cursus tellus nisi placerat enim. Etiam aliquam euismod finibus. Etiam vitae neque mi. Vivamus vulputate tortor ullamcorper massa maximus vestibulum. Mauris molestie lorem ante, ut hendrerit dui placerat et. In ornare eleifend nisl, eu ullamcorper eros ullamcorper nec. Maecenas commodo eget lacus et ullamcorper. Sed tristique metus mi, quis fermentum massa mattis semper. Suspendisse vel laoreet turpis. In pharetra scelerisque ante, at semper nibh. Integer dignissim sollicitudin ipsum at pulvinar. Fusce vitae mi turpis. Fusce nec magna malesuada, lobortis velit ac, sodales leo. Quisque eu eros varius, commodo arcu vel, lacinia mi. Etiam ullamcorper sapien quis tempus hendrerit. Aenean lacinia diam euismod urna convallis interdum. Aliquam velit risus, suscipit eget lacus et, interdum lacinia sem. Praesent euismod dapibus arcu, vitae iaculis quam semper ut. Vestibulum finibus dolor justo, in lacinia orci fringilla in. Aenean dui orci, fringilla pretium commodo at, condimentum sit amet arcu. Ut pellentesque orci nec nulla lacinia scelerisque. Vivamus hendrerit leo in maximus scelerisque. Sed non vulputate libero. Fusce id lectus sit amet dui pharetra lacinia.',
  'Sed vitae massa libero. Aliquam sed rhoncus arcu, sed lacinia ipsum. Sed sagittis, libero eget pretium scelerisque, nulla felis tempus risus, sit amet volutpat felis nibh eget odio. Praesent ipsum arcu, ultricies ac vestibulum a, finibus ac est. Proin bibendum eu tortor ac tempor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam consectetur orci vitae ultricies sagittis. Cras rutrum suscipit blandit. Aliquam sodales nibh ac mauris laoreet eleifend. In et vestibulum est, in semper odio. Duis at suscipit nunc. Cras id velit lectus. Cras a pellentesque mi. Sed mollis a erat ut luctus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque et suscipit dolor. Ut accumsan justo vitae porta commodo. Aliquam erat volutpat. Donec varius massa a neque feugiat maximus. Morbi consequat mattis lacus at tristique. Nullam eu mi nec erat bibendum vulputate sit amet at nunc. Duis et justo sit amet ex consectetur varius sit amet id erat.  Vivamus auctor in libero quis cursus. Fusce vehicula vehicula sem, et placerat velit mollis at. Etiam condimentum eu ipsum nec suscipit. Sed cursus risus metus, quis pretium orci porta sit amet. Nulla quis laoreet nibh, tempor faucibus ante. Suspendisse neque est, sodales et nulla tincidunt, ultrices pellentesque metus. Pellentesque erat ante, egestas sit amet mi id, vehicula venenatis elit. Aenean vel elementum justo. Cras molestie ipsum nisl, vel suscipit ante tempus vitae. Nulla vehicula lacus eu egestas tristique. In efficitur dictum pulvinar. Nam luctus tincidunt elit id ornare. Integer porttitor nec quam id tristique.',
  'Integer lacinia mollis lacus a ultrices. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut sagittis lectus suscipit erat tincidunt, suscipit imperdiet nunc sagittis. Fusce diam neque, venenatis et viverra quis, fringilla sed purus. Aliquam augue ipsum, euismod sit amet lorem et, consectetur venenatis sem. Praesent in tempus nisi, sed rhoncus ante. Sed et accumsan lorem. In et urna at nisi sollicitudin ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut elementum ante non bibendum viverra. Vestibulum vitae ligula tincidunt, lacinia elit vel, cursus sem. Donec dignissim viverra aliquam. Vestibulum fermentum molestie venenatis. Fusce tincidunt dui ligula, facilisis porta elit pulvinar non. Donec at purus metus. Praesent in massa interdum, euismod nisi vitae, placerat justo.',
  'Ut molestie venenatis dolor, et hendrerit purus. Nullam quis porttitor lorem. Donec euismod enim commodo nisl faucibus, vel egestas ante sagittis. Nullam ullamcorper tempor felis, molestie semper leo accumsan at. Curabitur sodales risus lacinia, faucibus eros ac, eleifend sem. Curabitur interdum ante eget eleifend condimentum. Sed ac bibendum est. Nulla facilisi. Cras sagittis ex vel risus accumsan, id vulputate orci blandit. Vestibulum dapibus faucibus neque, vel fermentum mi vestibulum non. Donec laoreet metus lectus, congue efficitur metus porttitor eu. Sed facilisis euismod aliquet. Ut sit amet rutrum risus. Nam et sagittis urna. Donec in tellus auctor diam feugiat dignissim vel non turpis.',
];
export const COURSE_DESCRIPTION = {
  title: 'Exercise №1: Background',
  info: 'On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain.',
};
