export const QUERY_KEYS = {
  courseAndMaterials: 'CourseAndMaterials',
  courseInfo: 'CourseInfo',
  coursesMap: 'CoursesMap',
  paginatedCoursesList: 'PaginatedCoursesList',
  myCourses: 'MyCourses',
  availableCourses: 'AvailableCourses',
  employeeProfile: 'EmployeeProfile',
  coursesRequests: 'CoursesRequests',
  employeesList: 'EmployeesList',
  profile: 'Profile',
  clientCourseInfo: 'ClientCourseInfo',
  paginatedClientCoursesList: 'PaginatedClientCoursesList',
  courseTest: 'CourseTest',
  getTestTime: 'GetTestTime',
  skills: 'Skills',
  adminTest: 'AdminTest',
  pendingAssessments: 'PendingAssessments',
  courseEditorData: 'CourseEditorData',
};
